In [1]:
import pandas as pd
import numpy as np
import matplotlib. pyplot as plt
import seaborn as sns
import warnings
%matplotlib inline

# z=sns.get_dataset_names()
df=sns.load_dataset('iris')
print(df)

     sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]


df.shape

In [2]:
df.shape

(150, 5)

In [3]:
df.head()

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    object 
dtypes: float64(4), object(1)
memory usage: 6.0+ KB


In [5]:
df.columns

Index(['sepal_length', 'sepal_width', 'petal_length', 'petal_width',
       'species'],
      dtype='object')

In [6]:
df.corr()

C:\Users\asimj\AppData\Local\Temp\ipykernel_7528\1134722465.py:1: FutureWarning: The default value of numeric_only in DataFrame.corr is deprecated. In a future version, it will default to False. Select only valid columns or specify the value of numeric_only to silence this warning.
  df.corr()


sepal_length  sepal_width  petal_length  petal_width
sepal_length      1.000000    -0.117570      0.871754     0.817941
sepal_width      -0.117570     1.000000     -0.428440    -0.366126
petal_length      0.871754    -0.428440      1.000000     0.962865
petal_width       0.817941    -0.366126      0.962865     1.000000

In [7]:
df.isnull().sum()

sepal_length    0
sepal_width     0
petal_length    0
petal_width     0
species         0
dtype: int64

In [8]:
df.value_counts('species')

species
setosa        50
versicolor    50
virginica     50
dtype: int64

In [9]:
df['species']=df['species'].replace({'setosa':0,'versicolor':1,'virginica':2})
print(df.head())

   sepal_length  sepal_width  petal_length  petal_width  species
0           5.1          3.5           1.4          0.2        0
1           4.9          3.0           1.4          0.2        0
2           4.7          3.2           1.3          0.2        0
3           4.6          3.1           1.5          0.2        0
4           5.0          3.6           1.4          0.2        0


In [10]:
df.head()

sepal_length  sepal_width  petal_length  petal_width  species
0           5.1          3.5           1.4          0.2        0
1           4.9          3.0           1.4          0.2        0
2           4.7          3.2           1.3          0.2        0
3           4.6          3.1           1.5          0.2        0
4           5.0          3.6           1.4          0.2        0

In [11]:
x=df.drop('species',axis=1)
y=df['species']
print(y.shape)
print(x.shape)

(150,)
(150, 4)


In [12]:
from sklearn.model_selection import train_test_split
x_train,x_test, y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=1)
x_test

sepal_length  sepal_width  petal_length  petal_width
14            5.8          4.0           1.2          0.2
98            5.1          2.5           3.0          1.1
75            6.6          3.0           4.4          1.4
16            5.4          3.9           1.3          0.4
131           7.9          3.8           6.4          2.0
56            6.3          3.3           4.7          1.6
141           6.9          3.1           5.1          2.3
44            5.1          3.8           1.9          0.4
29            4.7          3.2           1.6          0.2
120           6.9          3.2           5.7          2.3
94            5.6          2.7           4.2          1.3
5             5.4          3.9           1.7          0.4
102           7.1          3.0           5.9          2.1
51            6.4          3.2           4.5          1.5
78            6.0          2.9           4.5          1.5
42            4.4          3.2           1.3          0.2
92            5.8          2.6           4.0          1.2
66            5.6          3.0           4.5          1.5
31            5.4          3.4           1.5          0.4
35            5.0          3.2           1.2          0.2
90            5.5          2.6           4.4          1.2
84            5.4          3.0           4.5          1.5
77            6.7          3.0           5.0          1.7
40            5.0          3.5           1.3          0.3
125           7.2          3.2           6.0          1.8
99            5.7          2.8           4.1          1.3
33            5.5          4.2           1.4          0.2
19            5.1          3.8           1.5          0.3
73            6.1          2.8           4.7          1.2
146           6.3          2.5           5.0          1.9

In [13]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn import metrics
ran=RandomForestClassifier()
ran.fit(x_train,y_train)
y_pred=ran.predict(x_test)
y_pred
# ran.score(y_test,y_pred)

array([0, 1, 1, 0, 2, 1, 2, 0, 0, 2, 1, 0, 2, 1, 1, 0, 1, 1, 0, 0, 1, 1,
       2, 0, 2, 1, 0, 0, 1, 2], dtype=int64)

In [14]:
df.iloc[18]

sepal_length    5.7
sepal_width     3.8
petal_length    1.7
petal_width     0.3
species         0.0
Name: 18, dtype: float64

In [15]:
ran.predict([[2.2,4.6,4.5,3.1]])

E:\python 3.10.10new\lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(


array([2], dtype=int64)

In [16]:

print(metrics.accuracy_score(y_test, y_pred))

0.9666666666666667


In [17]:
logg=LogisticRegression()
logg.fit(x_train,y_train)


E:\python 3.10.10new\lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [18]:
l_pred=logg.predict(x_test)
l_pred

array([0, 1, 1, 0, 2, 1, 2, 0, 0, 2, 1, 0, 2, 1, 1, 0, 1, 1, 0, 0, 1, 1,
       2, 0, 2, 1, 0, 0, 1, 2], dtype=int64)